### ISSUE TITLE
Incorporar validación cuando no hay resultados de búsqueda

### ISSUE THREAD

**Issue by JCMiguel** [JCMiguel/repository-reviewer#42]
Cuando se realiza una búsqueda que no devuelve resultados desde la interfaz, se obtiene este error:

```bash
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\juanc\AppData\Local\Programs\Python\Python39\lib\tkinter\__init__.py", line 1892, in __call__
    return self.func(*args)
  File "D:\ArchivosPersonales\Workspace\repository-reviewer\venv\lib\site-packages\customtkinter\windows\widgets\ctk_button.py", line 554, in _clicked
    self._command()
  File "D:\ArchivosPersonales\Workspace\repository-reviewer\gui\querier_page.py", line 95, in querier_tab_search_btn_event
    querier.search(debug=True)
  File "D:\ArchivosPersonales\Workspace\repository-reviewer\engine\querier.py", line 111, in search
    self.append_partial_res(repo.search())
  File "D:\ArchivosPersonales\Workspace\repository-reviewer\historic\search.py", line 38, in append_partial_res
    self._report_data = self._report_data.merge_reports( results )
  File "D:\ArchivosPersonales\Workspace\repository-reviewer\historic\report.py", line 116, in merge_reports
    compound[item] = self._merge_list_or_tuple(other, item)
  File "D:\ArchivosPersonales\Workspace\repository-reviewer\historic\report.py", line 155, in _merge_list_or_tuple
    for idx in range(len(target)):
TypeError: object of type 'NoneType' has no len()
```

Es posible que un error similar ocurra cuando se invoca la aplicación desde consola.

**Comment by JCMiguel** [comment]
Posiblemente relacionado a issue #10
